language:
- objective-c
env:
  global: LATEST_TAG=1
  matrix:
  - VERSION=2.7.7 NUMPY_VERSION=1.6.0
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.1 NUMPY_VERSION=1.7.1
install:
- source terryfy/travis_tools.sh
- get_python_environment macpython $VERSION venv
- pip install -f $NIPY_WHEELHOUSE numpy==$NUMPY_VERSION cython wheel six
- cd scikit-image
- if [ -n "$LATEST_TAG" ]; then
  git fetch ; # fetch branches
  git fetch --tags ; # fetch tags not on branches
  git checkout `../terryfy/git-latest-tag` ;
  fi
- python setup.py bdist_wheel
- rename_wheels dist
- pip install dist/*.whl
- cd ..
script:
- pip install --no-index -f $NIPY_WHEELHOUSE nose scipy pillow matplotlib
- if [ "${VERSION:0:3}" != "3.3" ]; then pip install -U numpy; fi
- mkdir tmp_for_test
- cd tmp_for_test
- nosetests --exe -v skimage
- cd ..
before_deploy: cd scikit-image/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: UUmgPJxMIvdn5ByWI8PQFiT9Nge5/p1iP0ZNfpcG10/aKhYJzh4lwlsLfmTOepm8AwxM5dnJ5kcE5CTzShTBilyygxmo9cRe9ngiFN7SUmBSC+NUxd+OdTbTuCtuv5wwSg4m8ppzmvsp14FdSpb1Ax0A7et0XoRiEV1MlwDFqcQ=
  region: ORD
  container: wheels
  skip_cleanup: true
